apiVersion: v1
kind: Service
metadata:
  name: bookinfo-legacy
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    kubevirt.io/domain: bookinfo-legacy
    vm.kubevirt.io/name: bookinfo-legacy
  sessionAffinity: None
  type: ClusterIP
