apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hostpath-provisioner

resources:
- https://raw.githubusercontent.com/kubevirt/hostpath-provisioner-operator/main/deploy/namespace.yaml
- https://raw.githubusercontent.com/kubevirt/hostpath-provisioner-operator/main/deploy/webhook.yaml
- https://raw.githubusercontent.com/kubevirt/hostpath-provisioner-operator/main/deploy/operator.yaml
- https://github.com/kubevirt/hostpath-provisioner-operator/raw/main/deploy/hostpathprovisioner_cr.yaml
- https://github.com/kubevirt/hostpath-provisioner-operator/raw/main/deploy/storageclass-wffc-csi.yaml

patchesStrategicMerge:
- storageclass-patch.yaml
