apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo

resources:
- ../base
- https://raw.githubusercontent.com/Maistra/istio/maistra-2.1/samples/bookinfo/networking/bookinfo-gateway.yaml

patchesStrategicMerge:
- rating.yaml