apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datavolumes
spec:
  destination:
    namespace: kubevirt-os-images
    server: https://kubernetes.default.svc
  project: default
  source:
    path: datavolumes/overlays/kubernetes
    repoURL: https://github.com/cwilkers/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
